# Generated by Django 5.1.1 on 2024-09-15 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notice_and_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice_and_events',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notice_and_events',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notice_and_events',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_notices', to=settings.AUTH_USER_MODEL),
        ),
    ]
