# Generated by Django 5.1.1 on 2024-09-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notice_and_events_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_and_events',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
