# Generated by Django 5.1.1 on 2024-09-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notice_and_events_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='sem',
            field=models.IntegerField(default=0),
        ),
    ]
