# Generated by Django 5.1.1 on 2024-09-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_role_department_role_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='sem',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
